export const entregasIniciales = [
  {
    id: 1,
    cliente: "Juan Pérez",
    producto: "Papa",
    carga: "500 kg",
    origen: "Coracora",
    destino: "Puquio",
    direccion: "Av. Lima 123",
    estado: "En tránsito",
    monto: 250,
    ubicacion: "Km 35 - Coracora",
  },
  {
    id: 2,
    cliente: "María López",
    producto: "Queso",
    carga: "100 kg",
    origen: "Coracora",
    destino: "Nazca",
    direccion: "Jr. Arequipa 456",
    estado: "Entregado",
    monto: 180,
    ubicacion: "Entrega completada",
  },
  {
    id: 3,
    cliente: "Carlos Huamán",
    producto: "Ganado",
    carga: "3 animales",
    origen: "Coracora",
    destino: "Puquio",
    direccion: "Plaza principal",
    estado: "Pendiente",
    monto: 320,
    ubicacion: "Esperando recojo",
  },
];